apiVersion: v1
kind: Service
metadata:
  name: helloapp-svc
spec:
  type: NodePort
  selector:
    app: helloapp
  ports:
    - port: 8080
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - image: nareshdoniparti/kubernetes-with-spring:v4
          name: springhelloapp-container
          envFrom:
            - configMapRef:
                name: helloapp-config
              prefix: CONFIG_