apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - image: nareshdoniparti/kubernetes-with-spring:buggy
        name: springhelloapp-container
        readinessProbe:
          periodSeconds: 1
          successThreshold: 2
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080